<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        /*
        如何改变promise 的状态?
            (1) resolve(value): 如果当前是pendding 就会变为resolved
            (2) reject(reason): 如果当前是pendding 就会变为rejected
            (3) 抛出异常: 如果当前是pendding 就会变为rejected

        一个promise 指定多个成功/失败回调函数, 都会调用吗?
            当promise 改变为对应状态时都会调用
        */


        const p = new Promise((resolve, reject)=>{
            // resolve(1);//promise变为resolved成功状态
            // reject(1);////promise变为rejected失败状态
            // throw new Error('出错了');//抛出异常，promise变为rejected失败状态 reason为抛出的error
            throw 3;//抛出异常  promise 变为rejected失败状态  reason 为抛出的3 
        })
        // console.log(p);
        p.then(
            value=>{

            },
            reason =>{
                console.log('reason', reason);
            }
        )
        
        p.then(
            value=>{

            },
            reason =>{
                console.log('reason2', reason);
            }
        )

    </script>
</body>
</html>