<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise-封装__11-catch方法与异常穿透</title>
</head>
<body>
    <script src="./promise.js"></script>
    <script>
        let p = new Promise((resolve, reject)=>{
            setTimeout(()=>{
                resolve('OK');
                // reject('Error');
            }, 1000);
        });
        p.then()
        .then(value =>{
            console.log(111);
        }).then(value=>{
            console.log(222);
        }).then(value=>{
            console.log(333);
        }).catch(reason =>{
            console.warn(reason);
        })
        // console.log(res);
    </script>
</body>
</html>